### PR TITLE
Added missing support for endNumber inside MultipleSegmentBase

### PR DESCRIPTION
**Pull request by wreszelewski**
Hi!
Thanks for this lib! I needed to use endNumber property of MultipleSegmentBase, which was missing, so I added it.
Could you merge this into main repo and release new version to PyPi?

### CODE REVIEW

**Review by davemevans — APPROVED** [review]

**Comment by sangwonl** [comment]
Thanks @wreszelewski for your support.

By the way, I don't see the field `endNumber` from [DASH-MPD standard schema file](https://standards.iso.org/ittf/PubliclyAvailableStandards/MPEG-DASH_schema_files/DASH-MPD.xsd). So, I'm not sure if we can include this field. Can someone comment on it?

cc: @davemevans

**Comment by davemevans** [comment]
Seems that schema file available at that link has not been updated to match the 4th edition of the DASH spec - it only seems to match the 2nd edition.

4th Edition schema is available at https://standards.iso.org/iso-iec/23009/-1/ed-4/en/DASHSchema-4th-Ed.zip (link is in the spec) and includes `endNumber`.

**Comment by sangwonl** [comment]
> Seems that schema file available at that link has not been updated to match the current (4th) edition of the DASH spec - it only seems to match the 2nd edition.
> 
> 4th Edition schema is available at https://standards.iso.org/iso-iec/23009/-1/ed-4/en/DASHSchema-4th-Ed.zip (link is in the spec) and includes `endNumber`.

Thanks, now I understood. We need to update our schema file.

**Review by sangwonl — APPROVED** [review]
Thanks @wreszelewski for the updated thing, I will merge this PR.

PS) Will create an issue and follow the update.

**Pull request merged**
