### PR TITLE
Add cenc KID attribute to the Descriptor class (#47)

### PR DESCRIPTION
**Pull request by CASchneider**
Added the cenc KID attribute to the Descriptor class to identify cenc KID in the manifests of DRM encrypted content.

### CODE REVIEW

**Comment by rlaphoenix** [comment]
ns2 is an alternative to cenc. What if we do an or situation here instead of creating a cenc specific kid attribute? There's more than just ns2 and cenc as well, but I'm sort of blanking on remembering any more of them.

**Comment by rlaphoenix** [comment]
This issue is related to this pull request: https://github.com/sangwonl/python-mpegdash/issues/47

**Comment by davemevans** [comment]
The namespace can be anything, so no solution like this will cover all cases.

I do prefer having `cenc` to the random `ns2` that's currently supported since I imagine _most_ people will probably use namespace `cenc`, but the only way to really solve it is to make the parser namespace-aware which is probably unlikely.

It's totally possible for users to added support for elements from different namespaces by redefining classes. Sucks a bit, but keeps the core library cleaner.

**Review by sangwonl — DISMISSED** [review]
👍 Thanks

**Comment by sangwonl** [comment]
As far as I survey KIDs such like `ns2:default_KID` and `cenc:default_KID` belong to `ContentProtection` tag, right? If so, we'd better insert them to the specific tag rather than extending `Descriptor` broad.

But, if not, it would be appreciated if you share an MPD example for it.

**Comment by sangwonl** [comment]
Thanks @CASchneider for your contribution. But I believe that `ContentProtection` from #54 addresses this cenc attribute in general way. So I will close this PR for now. Thanks.

**Pull request closed without merging**
